### PR TITLE
Add docs and FastAPI dockerfile

### PR DESCRIPTION
**Pull request by KoalaGeo**
Hi @Rogerchandler highlighted this project to me earlier today.

Great work!  

I've done a couple of little things I thought might be useful: 

- I've created some docs using Docsify which works nicely with GitHub Pages in case the docs get larger. 
- I've also added a basic "hello world" type FastAPI dockerfile with python-ags4 installed. 

More work to do to get a web frontend and an API setup but it's a start. 

Hope to contribute further in the future if possible? 

Cheers :-)

### CODE REVIEW

**Comment by KoalaGeo** [comment]
Docs look like - http://koalageo.rocks/python-ags4/#/

**Comment by asitha-sena** [comment]
Hi Ed,
Thanks for the pull request and welcome to the project! It's great to have you on board.
The docsify page looks nice. I've been meaning to improve the docs for a while now and this seems like a good option. I like the fastAPI web app idea as well. 
I'll work on merging this with the master branch over the weekend.

**Comment by KoalaGeo** [comment]
Hi Asitha, 

No worries, realized after submitting, it might have been better if I'd done a PR for a docs branch, and a separate one for the docker+fast API particularly as thats not finished - although you can use the python-ags4 cli via 
`docker exec` so it's installed correctly on the docker image.

**Comment by asitha-sena** [comment]
Hi Edd,
I reviewed the code and it is ready to be merged, however I agree that it would be better to have separate branches so that we can make changes/updates with more freedom. I created two new branches named 'docs' and 'webapp'. Hope it won't be too much trouble to resubmit this pull request to those branches.

**Comment by KoalaGeo** [comment]
👍👍 I'll move things around in the next couple of days

**Comment by KoalaGeo** [comment]
Closing PR - See https://github.com/asitha-sena/python-ags4/pull/22 & https://github.com/asitha-sena/python-ags4/pull/23

**Pull request closed without merging**
